name: PHP code analysis

on:
    workflow_call:
        inputs:
            plugin-name:
                required: true
                type: string

jobs:
    php-code-analysis:
        name: Code analysis
        runs-on: ubuntu-latest
        env:
            PLUGIN_NAME: ${{ inputs.plugin-name }}

        container:
            image: ghcr.io/shopware5/docker-images-testing/install:shopware_5.7_8.0_8.2_none
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github_token }}

        steps:
            -   run: /usr/bin/supervisord -c /etc/supervisord.conf &

            -   name: Checkout ${{ env.PLUGIN_NAME }} test
                uses: actions/checkout@v3
                with:
                    path: plugin

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('plugin/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-


            -   name: Move plugin
                run: mv "$(pwd)/plugin" /shopware/custom/plugins/${{ env.PLUGIN_NAME }}

            -   name: Setup ${{ env.PLUGIN_NAME }}
                run: |
                    cd /shopware/custom/plugins/${{ env.PLUGIN_NAME }}
                    make composer-install
                    make install-plugin

            -   name: Execute PHP Code-Style-fixer
                run: |
                    cd /shopware/custom/plugins/${{ env.PLUGIN_NAME}}
                    make fix-cs-dry

            -   name: Execute PHP-Stan
                run: |
                    cd /shopware
                    php bin/console -e production -q # Initialise DIC (var/cache/production____REVISION____) for phpstan
                    cd custom/plugins/${{ env.PLUGIN_NAME }}
                    make phpstan
